route:
  group_by: ['alertname']
  group_wait: 60s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'https://webhook.site/cfc21a90-39ab-4ad2-a943-03358e864c77'